"""Unit tests for auto-generated stream entry IDs."""

import pytest

from app.storage.types import RedisStream


class TestAutoGeneratedIds:
    """Test auto-generated entry IDs in RedisStream."""

    def test_autogen_sequence_empty_stream_nonzero_timestamp(self):
        """Auto-generate sequence for empty stream with non-zero timestamp."""
        stream = RedisStream()
        result = stream.xadd("1-*", {"foo": "bar"})
        assert result == "1-0"

    def test_autogen_sequence_empty_stream_zero_timestamp(self):
        """Auto-generate sequence for empty stream with zero timestamp."""
        stream = RedisStream()
        result = stream.xadd("0-*", {"foo": "bar"})
        assert result == "0-1"

    def test_autogen_sequence_same_timestamp_increments(self):
        """Auto-generate sequence increments for same timestamp."""
        stream = RedisStream()
        result1 = stream.xadd("100-*", {"a": "1"})
        result2 = stream.xadd("100-*", {"a": "2"})
        result3 = stream.xadd("100-*", {"a": "3"})

        assert result1 == "100-0"
        assert result2 == "100-1"
        assert result3 == "100-2"

    def test_autogen_sequence_new_timestamp_resets(self):
        """Auto-generate sequence resets to 0 for new timestamp."""
        stream = RedisStream()
        stream.xadd("100-*", {"a": "1"})
        stream.xadd("100-*", {"a": "2"})
        result = stream.xadd("200-*", {"a": "3"})

        assert result == "200-0"

    def test_autogen_sequence_zero_timestamp_after_nonzero(self):
        """Auto-generate sequence uses 1 for zero timestamp even after entries."""
        stream = RedisStream()
        stream.xadd("100-5", {"a": "1"})
        # This will fail validation as 0 < 100, but let's test sequence generation
        # by checking what ID would be generated
        generated = stream._generate_entry_id("0-*")
        assert generated == "0-1"

    def test_autogen_full_wildcard(self):
        """Auto-generate both timestamp and sequence with *."""
        stream = RedisStream()
        result = stream.xadd("*", {"foo": "bar"})

        # Should be in format ms_time-0 (since empty stream and timestamp > 0)
        assert "-" in result
        ms_time, seq_num = result.split("-")
        assert int(ms_time) > 0
        assert seq_num == "0"

    def test_autogen_full_wildcard_multiple(self):
        """Auto-generate multiple entries with *."""
        stream = RedisStream()
        result1 = stream.xadd("*", {"a": "1"})
        result2 = stream.xadd("*", {"a": "2"})

        # Both should have valid IDs
        ms1, seq1 = result1.split("-")
        ms2, seq2 = result2.split("-")

        # Second entry should have >= timestamp
        assert int(ms2) >= int(ms1)

        # If same millisecond, sequence increments
        if ms1 == ms2:
            assert int(seq2) == int(seq1) + 1

    def test_mixed_explicit_and_autogen(self):
        """Mix explicit and auto-generated IDs."""
        stream = RedisStream()

        stream.xadd("1-0", {"a": "1"})
        result = stream.xadd("1-*", {"a": "2"})
        assert result == "1-1"

        stream.xadd("2-0", {"a": "3"})
        result = stream.xadd("2-*", {"a": "4"})
        assert result == "2-1"

    def test_autogen_validates_timestamp_format(self):
        """Auto-generate validates timestamp is numeric."""
        stream = RedisStream()

        with pytest.raises(ValueError, match="Invalid stream ID"):
            stream.xadd("abc-*", {"foo": "bar"})

    def test_autogen_validates_negative_timestamp(self):
        """Auto-generate rejects negative timestamp."""
        stream = RedisStream()

        with pytest.raises(ValueError, match="Invalid stream ID"):
            stream.xadd("-1-*", {"foo": "bar"})

    def test_generate_entry_id_no_wildcard(self):
        """_generate_entry_id returns explicit IDs unchanged."""
        stream = RedisStream()

        assert stream._generate_entry_id("123-456") == "123-456"
        assert stream._generate_entry_id("0-1") == "0-1"

    def test_get_next_sequence_empty_stream(self):
        """_get_next_sequence_number for empty stream."""
        stream = RedisStream()

        # Non-zero timestamp -> 0
        assert stream._get_next_sequence_number(100) == 0
        assert stream._get_next_sequence_number(1) == 0

        # Zero timestamp -> 1
        assert stream._get_next_sequence_number(0) == 1

    def test_get_next_sequence_existing_entries(self):
        """_get_next_sequence_number with existing entries."""
        stream = RedisStream()
        stream.xadd("100-5", {"a": "1"})

        # Same timestamp -> increment
        assert stream._get_next_sequence_number(100) == 6

        # Different timestamp (non-zero) -> 0
        assert stream._get_next_sequence_number(200) == 0

        # Different timestamp (zero) -> 1
        assert stream._get_next_sequence_number(0) == 1
